apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-0324
  labels:
    strimzi.io/cluster: cluster-a
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    max.message.bytes: 1048589
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: acl-user-10
  labels:
    strimzi.io/cluster: cluster-a
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "topic-0324"
          patternType: literal
        operations:
          - Read