apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: acl-user-10
  labels:
    strimzi.io/cluster: cluster-a
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "topic-0324"
          patternType: literal
        operations:
          - Read
      - resource:
          type: topic
          name: "topic-0324-01"
          patternType: literal
        operations:
          - Read
          - Write