apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-rack
spec:
  kafka:
    rack:
      topologyKey: topology.kubernetes.io/zone
    version: 3.1.0
    replicas: 4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 4
      transaction.state.log.replication.factor: 4
      transaction.state.log.min.isr: 2
      default.replication.factor: 4
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.1"
    storage:
      class: local-path
      size: 1Gi
      type: persistent-claim
  zookeeper:
    replicas: 1
    storage:
      class: local-path
      size: 1Gi
      type: persistent-claim
  entityOperator:
    topicOperator: {}
    userOperator: {}
